name: Build Desktop.js binaries

on:
  push:
    branches: [main]
    tags:
      - "v*"
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            triplet: x86_64-linux
          - os: ubuntu-22.04-arm
            triplet: aarch64-linux
          # - os: macos-latest
          #   triplet: aarch64-macos

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        if: startsWith(matrix.os, 'ubuntu-')
        run: |
          sudo apt-get update
          sudo apt install -y \
            libcurl4-openssl-dev build-essential cmake autoconf texinfo \
            libtool libltdl-dev git clang pkg-config make \
            libasound2-dev libx11-dev libxrandr-dev libxi-dev \
            libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev \
            libxinerama-dev libwayland-dev libxkbcommon-dev \
            libffi-dev
          clang --version

      - name: Build dependencies (Linux)
        if: startsWith(matrix.os, 'ubuntu-')
        run: |
          cd "$GITHUB_WORKSPACE"
          make install

      - name: Build project (Linux)
        if: startsWith(matrix.os, 'ubuntu-')
        env:
          TARGET_TRIPLET: ${{ matrix.triplet }}
        run: |
          cd "$GITHUB_WORKSPACE"
          make main

          mkdir -p build/
          mv djs-${{ matrix.triplet }} build/

      - name: Upload artifacts (per platform)
        uses: actions/upload-artifact@v4
        with:
          name: djs-${{ matrix.triplet }}
          path: build/

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Show files (debug)
        run: ls -R artifacts

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || 'nightly' }}
          files: artifacts/**/*
          overwrite_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
