name: Build Desktop.js binaries

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            triplet: x86_64-linux
            arch_name: x86_64
          - os: ubuntu-22.04-arm
            triplet: aarch64-linux
            arch_name: arm64
          # - os: macos-latest
          #   triplet: aarch64-macos

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        if: startsWith(matrix.os, 'ubuntu-')
        run: |
          sudo apt-get update
          sudo apt install -y build-essential cmake libffi-dev
          clang --version
      - name: Install dependencies (Linux)
        if: startsWith(matrix.os, 'ubuntu-')
        run: |
          cd "$GITHUB_WORKSPACE"
          make install

      - name: Build project (Linux)
        if: startsWith(matrix.os, 'ubuntu-')
        env:
          TARGET_TRIPLET: ${{ matrix.triplet }}
        run: |
          cd "$GITHUB_WORKSPACE"
          make main
          mkdir -p "$GITHUB_WORKSPACE/build"
          mv djs-* build/
